'''
exceptions.py: exceptions defined by Zoinks

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2020 by Michael Hucka and the California Institute of Technology.
This code is open-source software released under a 3-clause BSD license.
Please see the file "LICENSE" for more information.
'''


# Base class.
# .............................................................................
# The base class makes it possible to use a single test to distinguish between
# exceptions generated by Zoinks and exceptions generated by something else.

class ZoinksException(Exception):
    '''Base class for Zoinks exceptions.'''
    pass


# Exception classes.
# .............................................................................

class CannotProceed(ZoinksException):
    '''A recognizable condition caused an early exit from the program.'''
    pass

class UserCancelled(ZoinksException):
    '''The user elected to cancel/quit the program.'''
    pass

class NetworkFailure(ZoinksException):
    '''Unrecoverable problem involving network operations.'''
    pass

class ServiceFailure(ZoinksException):
    '''Unrecoverable problem involving a remote service.'''
    pass

class AuthenticationFailure(ZoinksException):
    '''Problem obtaining or using authentication credentials.'''
    pass

class InternalError(ZoinksException):
    '''Unrecoverable problem involving Zoinks itself.'''
    pass

class NotFound(ZoinksException):
    '''Item could not be found.'''
    pass

class FileError(ZoinksException):
    '''Problem reading or writing a file or its attributes.'''
    pass
